### ISSUE TITLE
Update to 1.16.4

### ISSUE THREAD

**Issue by XCraftTM** [BadlionClient/BadlionClientModAPI#13]
Can you update this Plugin to the 1.16.4 cause when you use the Plugin in the 1.16 it gives the Error:

```
[11:34:46 ERROR]: Could not pass event PlayerJoinEvent to BadlionClientModAPI v1.0
java.lang.NullPointerException: null
        at net.badlion.blcmodapibukkit.listener.PlayerListener.onPlayerJoin(PlayerListener.java:152) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-262]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-262]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-262]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-262]
        at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:273) ~[patched_1.16.4.jar:git-Paper-262]
        at net.minecraft.server.v1_16_R3.PlayerList.lambda$null$1(PlayerList.java:220) ~[patched_1.16.4.jar:git-Paper-262]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:165) ~[patched_1.16.4.jar:git-Paper-262]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:385) ~[patched_1.16.4.jar:git-Paper-262]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:145) ~[patched_1.16.4.jar:git-Paper-262]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1384) ~[patched_1.16.4.jar:git-Paper-262]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-262]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-262]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-262]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-262]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
```

Please look what the error is and then update please!

**Comment by PSNRigner** [comment]
Hey @XCraftTM, sorry for the late reply, can you check if there's any error when starting the plugin ?

Also on what exact version of spigot are you ? I tried reproducing it but it's all fine for me.

**Comment by PSNRigner** [comment]
Nevermind, got it to reproduce on latest PaperSpigot build.

**Comment by PSNRigner** [comment]
Has been fixed in the latest release : https://github.com/BadlionClient/BadlionClientModAPI/releases/tag/1.2.2
