### ISSUE TITLE
Failed to find EntityPlayer class bukkit/spigot/paper 1.17 open-jdk16

### ISSUE THREAD

**Issue by ZeNyfh** [BadlionClient/BadlionClientModAPI#21]
Errors on its own and with other plugins, version is also incorrect, I am running on the latest build (1.2.2) of BadlionClientModAPI.
I have been told that adding "--illegal-access=permit" to my startup parameters would fix the issue temporarily but it has not, I get the same error with and without the "temporary fix".

[03:56:43 ERROR]: Error occurred while enabling BadlionClientModAPI v1.0 (Is it up to date?)
java.lang.RuntimeException: Failed to find EntityPlayer class
	at net.badlion.blcmodapibukkit.listener.PlayerListener.<init>(PlayerListener.java:71) ~[?:?]
	at net.badlion.blcmodapibukkit.BlcModApiBukkit.onEnable(BlcModApiBukkit.java:40) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-"e31ad11"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-"e31ad11"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-"e31ad11"]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-"e31ad11"]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-"e31ad11"]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[patched_1.17.jar:git-Paper-"e31ad11"]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:303) ~[patched_1.17.jar:git-Paper-"e31ad11"]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-"e31ad11"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"e31ad11"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[03:56:43 INFO]: [BadlionClientModAPI] Disabling BadlionClientModAPI v1.0

**Comment by PSNRigner** [comment]
Hello, I'm currently working on fixing that issue, it's because of bukkit changes in 1.17 😃

**Comment by PSNRigner** [comment]
I just fixed that issue in [1.2.3](https://github.com/BadlionClient/BadlionClientModAPI/releases/tag/1.2.3)
