### ISSUE TITLE
On PaperMC 1.18.1 Not working

### ISSUE THREAD

**Issue by GammaPotato** [BadlionClient/BadlionClientModAPI#23]
Here is the Error on my Terminal

```
[21:21:05 INFO]: [BadlionClientModAPI] Enabling BadlionClientModAPI v1.0*
[21:21:05 INFO]: [BadlionClientModAPI] Found version v1_18_R1
[21:21:05 ERROR]: Error occurred while enabling BadlionClientModAPI v1.0 (Is it up to date?)
java.lang.RuntimeException: Failed to find EntityPlayer class
	at net.badlion.blcmodapibukkit.listener.PlayerListener.<init>(PlayerListener.java:71) ~[badlionclientmodapibukkit.jar:?]
	at net.badlion.blcmodapibukkit.BlcModApiBukkit.onEnable(BlcModApiBukkit.java:40) ~[badlionclientmodapibukkit.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[paper-1.18.1.jar:git-Paper-103]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[paper-1.18.1.jar:git-Paper-103]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.reload(CraftServer.java:1036) ~[paper-1.18.1.jar:git-Paper-103]
	at org.bukkit.Bukkit.reload(Bukkit.java:857) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897) ~[paper-1.18.1.jar:git-Paper-103]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchServerCommand(CraftServer.java:860) ~[paper-1.18.1.jar:git-Paper-103]
	at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:507) ~[paper-1.18.1.jar:git-Paper-103]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:481) ~[paper-1.18.1.jar:git-Paper-103]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-103]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-103]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-103]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:21:05 INFO]: [BadlionClientModAPI] Disabling BadlionClientModAPI v1.0
```

**Comment by PSNRigner** [comment]
Hey,

Paper 1.18.1 is now using a custom build system. We'll try to make it compatible as soon as possible 😃

**Comment by PSNRigner** [comment]
I just tested the 1.17 version of the plugin and it worked perfectly on the latest paper build from [https://papermc.io/downloads](https://papermc.io/downloads).

**Comment by PSNRigner** [comment]
Closing this since no user reply.
