### ISSUE TITLE
MC 1.18.1 - Error Causes Plugin to Be Disabled

### ISSUE THREAD

**Issue by iCaitlyn** [BadlionClient/BadlionClientModAPI#24]
Notes: Slightly different issue from #23 

The version of the plugin used is ["badlionclientmodapibukkit-1.17.jar"](https://github.com/BadlionClient/BadlionClientModAPI/releases/tag/1.2.3), 

Below is the error stack trace:
[CODE]
[20:58:59 INFO]: [BadlionClientModAPI] Enabling BadlionClientModAPI v1.0
[20:58:59 INFO]: [BadlionClientModAPI] Found version v1_18_R1
[20:58:59 ERROR]: Error occurred while enabling BadlionClientModAPI v1.0 (Is it up to date?)
java.lang.RuntimeException: Failed to find PlayerConnection.sendPacket()
        at net.badlion.blcmodapibukkit.listener.PlayerListener.<init>(PlayerListener.java:134) ~[badlionclientmodapibukkit-1.17.jar:?]
        at net.badlion.blcmodapibukkit.BlcModApiBukkit.onEnable(BlcModApiBukkit.java:38) ~[badlionclientmodapibukkit-1.17.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.18.1.jar:git-Paper-197]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-197]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[/CODE]

**Comment by iCaitlyn** [comment]
> Hey,
> 
> Can you try the new version of the ModApi, from the development branch ? It has received many bug fixes and improvements.
> 
> I've tested 1.18+ support there, and should be working fine 😃

Sure, may I know where the dev builds are located?

**Comment by PSNRigner** [comment]
They will be released later today. In the meantime, here's a build: [Badlion-ModApi-Bukkit-1.17.jar](https://i.rigner.ovh/Badlion-ModApi-Bukkit-1.17.jar)

**Comment by PSNRigner** [comment]
I just released the new ModApi, there are now official builds at https://github.com/BadlionClient/BadlionClientModAPI/releases/tag/2.0.0.

**Comment by iCaitlyn** [comment]
> They will be released later today. In the meantime, here's a manual build: [Badlion-ModApi-Bukkit-1.17.jar](https://i.rigner.ovh/Badlion-ModApi-Bukkit-1.17.jar)

It works now, thanks!
