### ISSUE TITLE
Detection broken on 1.20

### ISSUE THREAD

**Issue by Budderman18** [BadlionClient/BadlionClientModAPI#34]
No errors show in console at any point, but all mods cant be blocked.

**Comment by Budderman18** [comment]
This error is now showing up when anyone joins

java.lang.IllegalArgumentException: object is not an instance of declaring class
        at jdk.internal.reflect.DirectMethodHandleAccessor.checkReceiver(DirectMethodHandleAccessor.java:202) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:100) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at net.badlion.bukkitapi.BukkitPluginMessageSender.sendPluginMessagePacket(BukkitPluginMessageSender.java:168) ~[Badlion-ModApi-Bukkit-1.17.jar:?]
        at net.badlion.bukkitapi.listener.PlayerListener.onPlayerJoin(PlayerListener.java:33) ~[Badlion-ModApi-Bukkit-1.17.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor53.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:git-Paper-8]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.jar:git-Paper-8]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.jar:git-Paper-8]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:339) ~[paper-1.20.jar:git-Paper-8]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:593) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1575) ~[paper-1.20.jar:git-Paper-8]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.jar:git-Paper-8]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1396) ~[paper-1.20.jar:git-Paper-8]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.20.jar:git-Paper-8]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.20.jar:git-Paper-8]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]

**Comment by PSNRigner** [comment]
Thanks for the report, will investigate during the week

**Comment by LoneDev6** [comment]
player connection field changed from "b" to "c" on 1.20.1.

**Comment by PSNRigner** [comment]
Fixed in https://github.com/BadlionClient/BadlionClientModAPI/releases/tag/2.1.2
