### ISSUE TITLE
Support for 1.20.2

### ISSUE THREAD

**Issue by SirvydasS** [BadlionClient/BadlionClientModAPI#36]
ERROR and cant join to the server.

![image](https://github.com/BadlionClient/BadlionClientModAPI/assets/8950371/2e4f9337-0249-4b6f-b3a1-e52ac381ac68)
https://pastebin.com/uUGYN2mU

**Comment by Budderman18** [comment]
Results are different for everyone. Plugin instead refuses to enable for me with this:

org.bukkit.plugin.InvalidPluginException: java.lang.RuntimeException: Failed to find PacketPlayOutCustomPayload class
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[paper-1.20.2.jar:git-Paper-207]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.20.2.jar:git-Paper-207]
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.20.2.jar:git-Paper-207]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.2.jar:git-Paper-207]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.2.jar:git-Paper-207]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:512) ~[paper-1.20.2.jar:git-Paper-207]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.2.jar:git-Paper-207]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-207]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-207]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.RuntimeException: Failed to find PacketPlayOutCustomPayload class
	at net.badlion.bukkitapi.BukkitPluginMessageSender.<init>(BukkitPluginMessageSender.java:70) ~[Badlion-ModApi-Bukkit-1.17.jar:?]
	at net.badlion.bukkitapi.BukkitBadlionPlugin.<init>(BukkitBadlionPlugin.java:14) ~[Badlion-ModApi-Bukkit-1.17.jar:?]
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:88) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.20.2.jar:git-Paper-207]
	... 9 more

**Comment by PSNRigner** [comment]
Thanks I'll investigate, Mojang changed some packet classes in 1.20.2 unfortunately

**Comment by Budderman18** [comment]
bumping this as no work seemed to have been done despite this being a critical issue

**Comment by PSNRigner** [comment]
An internal ticket has been made for this issue, will be worked on this week

**Comment by PSNRigner** [comment]
Hey, I found time to work on that today, it should be working properly in the latest build here: https://github.com/BadlionClient/BadlionClientModAPI/releases/tag/2.1.3

Thanks for reporting the issue and sorry for the delay!
