### ISSUE TITLE
Detection broken on 1.20.5/6

### ISSUE THREAD

**Issue by Budderman18** [BadlionClient/BadlionClientModAPI#42]
plugin doesn't load on 1.20.6.

Error: 
 Could not load plugin 'Badlion-ModApi-Bukkit-1.17.jar' in folder 'plugins\.paper-remapped'
org.bukkit.plugin.InvalidPluginException: Exception initializing main class `net.badlion.bukkitapi.BukkitBadlionPlugin'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:106) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.20.6.jar:git-Paper-71]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.20.6.jar:git-Paper-71]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.20.6.jar:git-Paper-71]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.20.6.jar:git-Paper-71]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.6.jar:git-Paper-71]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:515) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-71]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        ... 10 more
Caused by: java.lang.RuntimeException: Failed to find version for running Minecraft server, got suffix craftbukkit
        at Badlion-ModApi-Bukkit-1.17.jar/net.badlion.bukkitapi.BukkitPluginMessageSender.<init>(BukkitPluginMessageSender.java:48) ~[Badlion-ModApi-Bukkit-1.17.jar:?]
        at Badlion-ModApi-Bukkit-1.17.jar/net.badlion.bukkitapi.BukkitBadlionPlugin.<init>(BukkitBadlionPlugin.java:14) ~[Badlion-ModApi-Bukkit-1.17.jar:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        ... 10 more

**Comment by Rigner** [comment]
Thanks for reporting, gonna investigate! I remember an article from Paper about changing some internal stuff that could affect some plugins, I think that's the case here

**Comment by Budderman18** [comment]
any updates on this?

**Comment by Rigner** [comment]
Sorry for the delay. I have implemented a fix, just need to test it on previous versions and then release it. Will do it today

**Comment by Rigner** [comment]
This should be fixed as part of https://github.com/BadlionClient/BadlionClientModAPI/releases/tag/2.1.5.
