### ISSUE TITLE
console error on join on spigot 1.8.8

### ISSUE THREAD

**Issue by coolpvpv1** [BadlionClient/BadlionClientModAPI#9]
when a player joins with this plugin on the server on spigot 1.8.8 it gives you this console error

[16:36:11 ERROR]: Could not pass event PlayerJoinEvent to BadlionClientModAPI v1.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.NullPointerException
        at net.badlion.blcmodapibukkit.listener.PlayerListener.onPlayerJoin(PlayerListener.java:152) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        ... 14 more

**Comment by Krymonota** [comment]
BadlionClientModAPI v1.0 is outdated and should no longer be used. [Please download and install the latest version](https://github.com/BadlionNetwork/BadlionClientModAPI/releases/tag/1.2.1) and check if this problem persists. If so, please provide the output of the `/version` command.

**Comment by coolpvpv1** [comment]
> BadlionClientModAPI v1.0 is outdated and should no longer be used. [Please download and install the latest version](https://github.com/BadlionNetwork/BadlionClientModAPI/releases/tag/1.2.1) and check if this problem persists. If so, please provide the output of the `/version` command.

i did install the latest version idk why it says v1.0

**Comment by coolpvpv1** [comment]
> BadlionClientModAPI v1.0 is outdated and should no longer be used. [Please download and install the latest version](https://github.com/BadlionNetwork/BadlionClientModAPI/releases/tag/1.2.1) and check if this problem persists. If so, please provide the output of the `/version` command.

and version is This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by Krymonota** [comment]
Oh, the version in the `plugin.yml` file never seems to be updated. Then either @PSNRigner or @mastergberry will have to address this issue. Sorry.

**Comment by PSNRigner** [comment]
Hello, is it still an issue ?

**Comment by marin-01** [comment]
Yes, I just tried to enable schematica but I can't because of that issue. Downloaded the latest version, running on Spigot 1.8.8.

**Comment by PSNRigner** [comment]
Alright, I'll try to test that.

**Comment by TouchBrown** [comment]
this is still an issue on 1.12.2 aswell.  Any idea when it will be fixed?

**Comment by PSNRigner** [comment]
I just checked the code, this is not supposed to happen unless spigot was modified since the plugin was made. Can one of guy send me a full server log at [loic@badlion.net](loic@badlion.net) ? It will stay confidential, It's just that I need to see if there were any other error related to that plugin, especially on boot.

**Comment by TouchBrown** [comment]
> I just checked the code, this is not supposed to happen unless spigot was modified since the plugin was made. Can one of guy send me a full server log at [loic@badlion.net](mailto:loic@badlion.net) ? It will stay confidential, It's just that I need to see if there were any other error related to that plugin, especially on boot.

so regarding this when it happened I was just using one of the tagged builds, but then I just compiled and it's fine.  I think you just need to put a new build out for whatever reason.  Idk what would have changed it.

**Comment by PSNRigner** [comment]
That's weird, becase the latest release (16 months ago) is the same as the current code https://github.com/BadlionClient/BadlionClientModAPI/releases/tag/1.2.1

**Comment by TouchBrown** [comment]
Well as noted above it was miss versioned so I changed that, but that's all I did to it and it worked.  This shouldn't have changed anything as far as I'm aware.

**Comment by PSNRigner** [comment]
Alright, thanks for the feedback
